Implement importance-sampled Disney and Microfacet BRDF, Optimize surfaceNormal computation, Add headlight support for NEE MIS, Refactor Code
chrismile/CloudRendering pull request #3
Opened 2024-07-12 16:30 UTC by JI20

This PR adds changes from the following Pull Requests (sorted from newest to oldest) into the upstream repository.

1. Code Cleanup
https://github.com/JI20/CloudRendering/pull/32

2. Headlight Support
https://github.com/JI20/CloudRendering/pull/28

3. Smoother Trilinear Gradient Interpolation
https://github.com/JI20/CloudRendering/pull/19

4. Next Event Estimation Support for Microfacet and Disney BRDF
https://github.com/JI20/CloudRendering/pull/16

5. Implement Microfacet (Cook-Torrance) BRDF and Disney BRDF (2012)
https://github.com/JI20/CloudRendering/pull/5

2024-07-12 19:23 UTC, chrismile requested changes
Looks good so far. I adapted some code, but need some clarification regarding "TODO: Auch weightOut is falsch beim Headlight". If I see it correctly, "pdfLightNee" is used also in the headlight case where it is not set?

2024-07-12 20:03 UTC, JI20 commented on Data/Shaders/VPT/VptUtils.glsl
> +
The problem the comment described with weightOut is already solved, since it is set to it's limit, 1.0, in the case of sampling the headlight.

2024-07-12 20:05 UTC, JI20 commented on Data/Shaders/VPT/VptUtils.glsl
> +                        2.0 * throughput * rdfNee * weightNee / pdfLightNee *
pdfLightNee is only not set if we actually sample the headlight, therefore it is defined here, see https://github.com/JI20/CloudRendering/blob/d9b1d098e6d412ed9fb99e2f96ef71f165693cd2/Data/Shaders/VPT/VptUtils.glsl#L980-L990

2024-07-12 20:06 UTC, JI20 commented on Data/Shaders/VPT/VptUtils.glsl
> +
I removed the unnecessary comment.

2024-07-13 09:42 UTC, chrismile approved these changes
Looks all good now.

2024-07-13 09:43 UTC, merged